---
title: "DataFromDGAPTwitter"
output: html_document
---

1. Load Require Packages

```{r}

load.package <- function(package.name){
  package.name = as.character(substitute(package.name))
  if(require(package.name, character.only = TRUE)) { 
    message(paste(package.name, ' loaded', sep = ""))
  } else {
    install.packages(package.name)
  }
}

```



2.  function to load data

```{r}

load.data <- function(url, type = "xml", file.name, overwrite = FALSE){
  load.package(RCurl)
  
  if(file.exists(file.name) & overwrite == FALSE){
    # print(1)
    return(readRDS(file.name))
  } else {
    # print(2)
    var <- switch(type,                     #add additional data sources here
                 xml  = xmlParse(url),
                 json = getURL(url))       #check if correct! Pass apa.api urls?
    saveRDS(var, file = file.name)
    return(var)
  }
}



```


3. query of presse portal (currently the query is hard coded. We have to make it customizable based upon the argumets)

```{r}

query <- "http://api.presseportal.de/api/ir/adhoc?api_key=e79c7f82be0b69ec33710a6f5b1651f2&limit=50&start=0&format=json&lang=de&teaser=1"


```


4. get the data for query

```{r}


json.data.from.presse.portal <- load.data(query, type = "json", file.name = "data.json", overwrite = TRUE)

load.package(rjson)
require(rjson)

r.object.json.data <- fromJSON(print(quote=F,json.data.from.presse.portal))

r.object.json.data$content

```
